version: "3.9"
services:

  schedulerapi:
    image: assistantnetschedulerapi:latest
    container_name: schedulerapi
    environment:
      - ConnectionStrings__StorageDatabase=mongodb://mongo:27017/
      - ConnectionStrings__RemoteMessageHandler=mongodb://mongo:27017/
    ports:
      - 5101:80
    expose:
      - 5101
    restart: always
    depends_on:
      - mongo

  schedulereventhandler:
    image: assistantnetschedulereventhandler:latest
    container_name: schedulereventhandler
    environment:
      - ConnectionStrings__StorageDatabase=mongodb://mongo:27017/
      - ConnectionStrings__RemoteMessageHandler=mongodb://mongo:27017/
    restart: always
    depends_on:
      - mongo

  mongo:
    image: mongo
    container_name: mongo
    volumes:
      - mongodb-data:/data
    ports:
      - 27017:27017
    expose:
      - 27017
    restart: always

volumes:
  mongodb-data:
