version: "3.9"
services:

  schedulerapi:
    image: assistantnetschedulerapi:latest
    container_name: schedulerapi
    environment:
      - ConnectionStrings__StorageDatabase=mongodb://mongo:27017/
    ports:
      - 5101:80
    expose:
      - 5101
    restart: always
    depends_on:
      - mongo

  schedulerservice:
    image: assistantnetschedulerservice:latest
    container_name: schedulerservice
    environment:
      - ConnectionStrings__StorageDatabase=mongodb://mongo:27017/
      - HttpClient__RemoteMessageHandler__BaseAddress=http://schedulerapi:5101/api
      - HttpClient__RemoteMessageHandler__Timeout=00:05
    restart: always
    depends_on:
      - mongo

  mongo:
    image: mongo
    container_name: mongo
    volumes:
      - mongodb-data:/data
    ports:
      - 27017:27017
    expose:
      - 27017
    restart: always

volumes:
  mongodb-data:
